CREATE TABLE IF NOT EXISTS technologies (
    id BIGSERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(90) NOT NULL
);

INSERT INTO technologies (nombre, descripcion)
SELECT nombre, descripcion FROM (VALUES
    ('Angular', 'Framework frontend'),
    ('React', 'Librería frontend'),
    ('Vue', 'Framework progresivo'),
    ('Node.js', 'Entorno de ejecución'),
    ('Django', 'Framework backend en Python'),
    ('Spring Boot', 'Framework backend en Java'),
    ('Laravel', 'Framework backend en PHP'),
    ('PostgreSQL', 'Base de datos relacional'),
    ('MongoDB', 'Base de datos NoSQL'),
    ('Redis', 'Almacenamiento en memoria'),
    ('Express.js', 'Framework backend minimalista'),
    ('Flask', 'Microframework para Python'),
    ('Ruby on Rails', 'Framework para Ruby'),
    ('ASP.NET', 'Framework de Microsoft'),
    ('Swift', 'Lenguaje de Apple'),
    ('Kotlin', 'Lenguaje para Android'),
    ('Flutter', 'Framework para apps móviles'),
    ('TensorFlow', 'Biblioteca de ML'),
    ('PyTorch', 'Framework de aprendizaje profundo'),
    ('GraphQL', 'Lenguaje de consulta para APIs'),
    ('gRPC', 'Framework de comunicación'),
    ('Kafka', 'Plataforma de streaming'),
    ('RabbitMQ', 'Sistema de mensajería'),
    ('Elasticsearch', 'Motor de búsqueda'),
    ('Kibana', 'Visualización de datos'),
    ('Prometheus', 'Monitoreo y alertas'),
    ('Grafana', 'Visualización de métricas'),
    ('Docker', 'Contenedores'),
    ('Kubernetes', 'Orquestación de contenedores'),
    ('Terraform', 'Infraestructura como código'),
    ('Ansible', 'Automatización de configuración'),
    ('Puppet', 'Gestión de configuración'),
    ('Chef', 'Automatización de infraestructura'),
    ('Nginx', 'Servidor web y proxy'),
    ('Apache', 'Servidor web'),
    ('Cassandra', 'Base de datos distribuida'),
    ('Hadoop', 'Procesamiento de big data'),
    ('Spark', 'Motor de procesamiento de datos'),
    ('Flink', 'Procesamiento de datos en tiempo real'),
    ('HBase', 'Base de datos distribuida'),
    ('CouchDB', 'Base de datos NoSQL'),
    ('Neo4j', 'Base de datos de grafos'),
    ('ArangoDB', 'Base de datos multimodelo'),
    ('D3.js', 'Visualización de datos'),
    ('Three.js', 'Gráficos 3D en la web'),
    ('WebGL', 'Gráficos 3D en navegadores'),
    ('Unity', 'Motor de juegos'),
    ('Unreal Engine', 'Motor de juegos'),
    ('Cocos2d', 'Framework de juegos'),
    ('OpenCV', 'Visión por computadora'),
    ('Pandas', 'Manipulación de datos en Python'),
    ('NumPy', 'Computación numérica en Python'),
    ('SciPy', 'Ciencia de datos en Python'),
    ('Matplotlib', 'Gráficos en Python'),
    ('Seaborn', 'Visualización de datos en Python'),
    ('XGBoost', 'Aprendizaje automático'),
    ('LightGBM', 'Aprendizaje automático rápido'),
    ('CatBoost', 'Modelo de aprendizaje automático'),
    ('Jupyter', 'Notebooks interactivos'),
    ('Google Colab', 'Notebooks en la nube'),
    ('Hugging Face', 'Modelos de lenguaje'),
    ('OpenAI', 'Modelos de IA'),
    ('IBM Watson', 'IA empresarial'),
    ('Azure ML', 'Machine Learning en la nube'),
    ('AWS SageMaker', 'Plataforma de ML en AWS'),
    ('Snowflake', 'Almacenamiento de datos en la nube'),
    ('BigQuery', 'Consulta de datos en la nube'),
    ('Redshift', 'Almacén de datos en AWS'),
    ('Looker', 'Análisis de datos'),
    ('Tableau', 'Visualización de datos'),
    ('Power BI', 'Visualización de datos de Microsoft'),
    ('QlikView', 'Plataforma de BI'),
    ('SAP Hana', 'Base de datos en memoria'),
    ('Oracle', 'Base de datos empresarial'),
    ('MySQL', 'Base de datos relacional'),
    ('MariaDB', 'Fork de MySQL'),
    ('SQLite', 'Base de datos ligera'),
    ('Firebird', 'Base de datos SQL'),
    ('IBM DB2', 'Base de datos empresarial'),
    ('CockroachDB', 'Base de datos distribuida'),
    ('VoltDB', 'Base de datos en memoria'),
    ('TimescaleDB', 'Base de datos de series temporales'),
    ('InfluxDB', 'Base de datos de series temporales'),
    ('RethinkDB', 'Base de datos en tiempo real'),
    ('FAISS', 'Búsqueda en grandes conjuntos de datos'),
    ('PyQt', 'Interfaz gráfica en Python'),
    ('GTK', 'Interfaz gráfica en Linux'),
    ('Qt', 'Framework multiplataforma'),
    ('Electron', 'Apps de escritorio con web'),
    ('Tauri', 'Alternativa a Electron'),
    ('Svelte', 'Framework de frontend'),
    ('SolidJS', 'Framework de frontend'),
    ('Alpine.js', 'Framework de frontend ligero'),
    ('HTMX', 'Interacción sin JavaScript complejo'),
    ('Livewire', 'Framework para Laravel'),
    ('Phoenix', 'Framework en Elixir'),
    ('Rust', 'Lenguaje de programación seguro'),
    ('Go', 'Lenguaje eficiente para servidores'),
    ('Clojure', 'Lenguaje funcional en JVM')
) AS temp(nombre, descripcion)
WHERE NOT EXISTS (SELECT 1 FROM technologies);
